[package]
name = "nevermind"
description = "mind maps as code"
license = "MIT"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
yaml-rust = "0.4.5"
